[pytest]
testpaths = scripts/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    integration: integration tests that may depend on external services or working DB
    slow: tests that take more than 5 seconds
